### ISSUE TITLE
It Just Keeps Loading On My New 2ds XL

### ISSUE THREAD

**Issue by Janter1603** [coderman64/netsurf-3ds#3]
![IMG_20240515_022137](https://github.com/coderman64/netsurf-3ds/assets/140511663/5ef7a93d-312b-4ac4-a1b5-4d13cee2efff)
as you can see above (probably(first time adding issue))
iv'e made the folders in 3DShell
the 3dsx is in /3ds
here's a video demonstrating my issue

https://github.com/coderman64/netsurf-3ds/assets/140511663/a8113eaf-dfe1-429f-b64d-9998660ebe8b

**Comment by Janter1603** [comment]
um, hello?? i've had this issue for 3 week's and no solution has ben given to me, WHAT'S HAPPENING!!

**Comment by AirplanegoBrr** [comment]
Did you try what the fix for #2 is? (https://github.com/coderman64/netsurf-3ds/issues/2#issuecomment-2024175250)

L+DPAD DOWN+SELECT (Open Rosalina menu)
Miscellaneous options -> `Update time and date via NTP` (make sure to set your offset) -> Press `A`

This is my only feedback other wise I have no clue, this was my fix.

**Comment by coderman64** [comment]
Apologies for the wait. Life is busy. 

You need to put all the stuff in the resources zip **_DIRECTLY_** in `/share/netsurf/`, NOT in a "Resources" folder under that path. i.e. you should have "/share/netsurf/internal.css" not "/share/netsurf/Resources/internal.css", etc.

I know that extracting certain files to a specific directory can be confusing (I'm serious) since many people ask you to do that and expect you to do exactly what you did here. If you can think of any clearer way to write the instructions, let me know.

The problem is that, since netsurf can't find this data, it can't load any webpage, including the error page. So the browser is just loading a webpage, finding an error, loading the error webpage, finding another error, ad infinitum.

Beyond that,  @AirplanegoBrr is correct, setting the wrong time on your 3DS will also cause issues, since https websites will all appear to either be from the future, or way in the past, causing any security-respecting application to go "hey wait a minute" and not actually load the webpage.

**Comment by Anonymous941** [comment]
Maybe it could be made easier by having netsurf extract the .zip automatically, and then just tell people to copy-paste the .zip file into `/3ds/netsurf`?  Just a thought

**Comment by Janter1603** [comment]
Success!!, NetSurf Now Loads! Graditude to you @coderman64
